name: cinepedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  #* Gestor de estado
  get: ^4.6.6
  flutter_riverpod: ^2.5.1
  # animaciones
  animate_do: ^3.3.4
  # Shimmer
  shimmer: ^3.0.0
  # Dar formato a numeros o valores
  intl: ^0.19.0
  # Manejar variables de entorno (.env)
  flutter_dotenv: ^5.1.0
  # Carrucel de imagenes (widgets)
  card_swiper: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  # Peticiones http
  dio: ^5.5.0+1
  # Reproductor de videos de youtube
  youtube_player_flutter: ^9.1.1

  #^ Base de datos local
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  #^ Base de datos local
  build_runner: ^2.4.12
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - .env #! Variables de entorno
